food/views.py
from flask import Blueprint,render_template, request, redirect, url_for, flash
from models import db, FOOD, User, FOOD_NEEDED
from forms import FoodForm,FoodNeededForm
from flask_login import login_required, current_user

food_bp = Blueprint('food', __name__, url_prefix='/food')

@food_bp.route("/index")
@login_required
def index():
    foods = FOOD.query.filter_by(user_id = current_user.id).all()
    return render_template("food/index.html", foods=foods)

@food_bp.route("/food/create", methods=["POST","GET"])
@login_required
def create():
    form = FoodForm()
    if form.validate_on_submit():
        name = form.name.data
        category = form.category.data
        date = form.date.data
        memo = form.memo.data
        food = FOOD(name=name, category=category, date=date, memo=memo, user_id = current_user.id)
        db.session.add(food)
        db.session.commit()
        
        flash("Registration Succeeded!")
        
        return redirect(url_for("food.index"))
    return render_template("food/create_form.html", form=form)

@food_bp.route("/food/update/<int:food_id>", methods=["POST","GET"])
@login_required
def update(food_id):
    target_data = FOOD.query.filter_by(id=food_id, user_id=current_user.id).first_or_404()
    form = FoodForm(obj=target_data)
    
    if request.method == "POST" and form.validate():
        target_data.name = form.name.data
        target_data.category = form.category.data
        target_data.date = form.date.data
        target_data.memo = form.memo.data
        db.session.commit()
        
        flash("Edit Succeeded!")
        
        return redirect(url_for("food.index"))
    return render_template("food/update_form.html",form=form, edit_id=target_data.id)

@food_bp.route("/food/delete/<int:food_id>")
@login_required
def delete(food_id):
    food = FOOD.query.filter_by(id=food_id, user_id=current_user.id).first_or_404()
    db.session.delete(food)
    db.session.commit()
    
    flash("Delete Succeeded!")
    
    return redirect(url_for("food.index"))

templates/food/create_form.html
{% extends "base.html" %}

{% block content %}
    <h1 class="my-4">Add Ingredients</h1>
    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('food.create') }}" novalidate>
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ render_field(form.name, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.category, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.date, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.memo, class="form-control", rows=5) }}
        </div>
        <div class="mb-3 d-flex justify-content-end">
            {{ form.submit(class="btn btn-primary me-2") }}
            <a href="{{ url_for('food.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock %}

templates/food/index.html
{% extends "base.html" %}

{% block content %}
    <style>
        .Expire_date {
            color: green;
            text-align: center;
        }
        .list-group {
            width: 60%;
            margin: auto;
        }
        h1 {
            text-align: center;
        }
        li {
            width: auto;
        }
    </style>
    
    <div class="container">
        <h1 class="my-4">Food List</h1>
        {% if foods == [] %}
            <p>No Food Here</p>
        {% else %}
            <ul class="list-group mb-4">
                {% for food in foods %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>{{ food.name }}</strong>
                        <div class="Expire_date d-flex justify-content-center flex-column align-items-center">
                            Expire Date:{{food.date}}
                        </div>
                        <div>
                            <a href="{{ url_for('food.update', food_id=food.id) }}" class="btn btn-warning btn-sm">Edit</a>
                            <a href="{{ url_for('food.delete', food_id=food.id) }}" class="btn btn-danger btn-sm">Delete</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        <div class="text-center">
            <a href="{{ url_for('food.create') }}" class="btn btn-primary" role="button">Add</a>
        </div>
    </div>
{% endblock %}

templates/food/update_form.html
{% extends "base.html" %}

{% block content %}
    <h1 class="my-4">Edit</h1>
    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('food.update', food_id=edit_id) }}" novalidate>
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ render_field(form.name, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.category, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.date, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.memo, class="form-control", rows=5) }}
        </div>
        <div class="mb-3 d-flex justify-content-end">
            {{ form.submit(class="btn btn-primary me-2") }}
            <a href="{{ url_for('food.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock %}