wish/views.py
from flask import Blueprint,render_template, request, redirect, url_for, flash
from models import db, FOOD, User, FOOD_NEEDED
from forms import FoodForm,FoodNeededForm
from flask_login import login_required, current_user

wish_bp = Blueprint('wish', __name__, url_prefix='/wish')

@wish_bp.route("/index")
@login_required
def index_wish():
    foods = FOOD_NEEDED.query.filter_by(user_id = current_user.id).all()
    return render_template("wish/needs.html", foods_needed=foods)

@wish_bp.route("/create", methods=["POST","GET"])
@login_required
def create_wish():
    form = FoodNeededForm()
    if form.validate_on_submit():
        name = form.name.data
        memo = form.memo.data
        food = FOOD_NEEDED(name=name, memo=memo, user_id = current_user.id)
        db.session.add(food)
        db.session.commit()
        
        flash("Registration Succeeded!")
        
        return redirect(url_for("wish.index_wish"))
    return render_template("wish/create_wish.html", form=form)

@wish_bp.route("/update/<int:food_id>", methods=["POST","GET"])
@login_required
def update_wish(food_id):
    target_data = FOOD_NEEDED.query.filter_by(id=food_id, user_id=current_user.id).first_or_404()
    form = FoodNeededForm(obj=target_data)
    
    if request.method == "POST" and form.validate():
        target_data.name = form.name.data
        target_data.memo = form.memo.data
        db.session.commit()
        
        flash("Edit Succeeded!")
        
        return redirect(url_for("wish.index_wish"))
    return render_template("wish/update_wish.html",form=form, edit_id=target_data.id)

@wish_bp.route("/delete/<int:food_id>")
@login_required
def delete_wish(food_id):
    food = FOOD_NEEDED.query.filter_by(id=food_id, user_id=current_user.id).first_or_404()
    db.session.delete(food)
    db.session.commit()
    
    flash("Delete Succeeded!")
    
    return redirect(url_for("wish.index_wish"))

templates/wish/create_wish.html
{% extends "base.html" %}

{% block content %}
    <h1 class="my-4">Add WishFood</h1>
    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('wish.create_wish') }}" novalidate>
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ render_field(form.name, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.memo, class="form-control", rows=5) }}
        </div>
        <div class="mb-3 d-flex justify-content-end">
            {{ form.submit(class="btn btn-primary me-2") }}
            <a href="{{ url_for('wish.index_wish') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock %}

templates/wish/needs.html
{% extends "base.html" %}

{% block content %}
    <style>
        .Expire_date {
            color: green;
            text-align: center;
        }
        .list-group {
            width: 60%;
            margin: auto;
        }
        h1 {
            text-align: center;
        }
        li {
            width: auto;
        }
    </style>
    
    <div class="container">
        <h1 class="my-4">WishList</h1>
        {% if foods_needed == [] %}
            <p>No Food Here</p>
        {% else %}
            <ul class="list-group mb-4">
                {% for food in foods_needed %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <strong>{{ food.name }}</strong>
                        <div>
                            <a href="{{ url_for('wish.update_wish', food_id=food.id) }}" class="btn btn-warning btn-sm">Edit</a>
                            <a href="{{ url_for('wish.delete_wish', food_id=food.id) }}"  class="btn btn-success btn-sm">Check</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        <div class="text-center">
            <a href="{{ url_for('wish.create_wish') }}" class="btn btn-primary" role="button">Add</a>
        </div>
    </div>
{% endblock %}

templates/wish/update_wish.html
{% extends "base.html" %}

{% block content %}
    <h1 class="my-4">Edit</h1>
    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('wish.update_wish', food_id=edit_id) }}" novalidate>
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ render_field(form.name, class="form-control") }}
        </div>
        <div class="mb-3">
            {{ render_field(form.memo, class="form-control", rows=5) }}
        </div>
        <div class="mb-3 d-flex justify-content-end">
            {{ form.submit(class="btn btn-primary me-2") }}
            <a href="{{ url_for('wish.index_wish') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock %}