recipe/views.py
from flask import Blueprint,render_template, request, redirect, url_for, flash
from models import db, FOOD, User, FOOD_NEEDED
from forms import FoodForm,FoodNeededForm
from flask_login import login_required, current_user

recipe_bp = Blueprint('recipe', __name__, url_prefix='/recipe')

@recipe_bp.route("/search")
@login_required
def search():
    
    return render_template("recipe/search.html")

templates/_formhelpers.html
{% macro render_field(field, class='') %}
    <dt>{{ field.label }}</dt>
    <dd>{{ field(class=class, **kwargs)|safe }}</dd>
    {% if field.errors %}
    <ul class="text-danger">
        {% for error in field.errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endmacro %}

templates/auth_base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Kitchen Keeper</title>
</head>
<style>
    body{
        background-color: #f5fbf8;
    }
</style>
<body>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}       
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Kitchen Keeper</title>
</head>
<body>
    <style>
        body{
            background-color: #f5fbf8;
        }

        nav{
            background-color: #1d5a3c;
        }
    </style>
    {% if current_user.is_authenticated %}

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Kitchen Keeper</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <li><a class="nav-link" href="{{ url_for('food.index') }}">FoodList</a></li>
                        <li><a class="nav-link" href="{{ url_for('wish.index_wish') }}">WishList</a></li>
                        <li><a class="nav-link" href="{{ url_for('recipe.search') }}">Recipe</a></li>
                        <li><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% endif %}
    <div class="container mt-4">
        {% block content %}{% endblock %}       
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Kitchen Keeper</title>
</head>
<style>
    body{
        background-color: #F5FFFA;
    }
    .menu{
        text-align: center;
        width: 40%;
    }
</style>
<body>
    <div class="container menu my-4 d-flex justify-content-center align-items-center"> <!-- d-flex, justify-content-center, align-items-centerを追加 -->
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Welcome to Kitchen Keeper</h4>
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">If you already have an account, please login.</div>
                        <a href="{{ url_for('auth.login') }}" class="btn btn-primary mt-2">Login</a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">If you don't have an account, please register.</div>
                        <a href="{{ url_for('auth.register') }}" class="btn btn-success mt-2">Signup</a>  
                    </div>
                </div>        
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>